import 'reflect-metadata';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { DataSource } from 'typeorm';
import { AddCampaignBriefs1753400000000 } from '../src/migrations/1753400000000-add-campaign-briefs';
import { CampaignContentService } from '../src/campaign-content/campaign-content.service';
import { blankBrief } from '../src/campaign-content/campaign-content.model';
import {AddContentConcepts1753500000000} from '../src/migrations/1753500000000-add-content-concepts';
import {ContentConceptService} from '../src/campaign-content/content-concept.service';

test('brief lifecycle: scoped access, frozen sharing, concurrency and revocation', {skip: !process.env.CAMPAIGN_TEST_DATABASE_URL}, async () => {
  const url = process.env.CAMPAIGN_TEST_DATABASE_URL!;
  assert.ok(['localhost','127.0.0.1'].includes(new URL(url).hostname));
  const schema = `brief_test_${randomUUID().replace(/-/g,'')}`;
  const root = await new DataSource({type:'postgres',url}).initialize();
  await root.query(`CREATE SCHEMA ${schema}`);
  const db = await new DataSource({type:'postgres',url,extra:{options:`-c search_path=${schema}`}}).initialize();
  try {
    await db.query('CREATE TABLE tch_campaign(id bigint PRIMARY KEY,name text,brand text)');
    await db.query("INSERT INTO tch_campaign VALUES(1,'Coffee','Daybreak'),(2,'Other','Other')");
    await db.query('CREATE TABLE tch_creator(id bigint PRIMARY KEY,name text)');
    await db.query("INSERT INTO tch_creator VALUES(1,'Creator'),(2,'Other')");
    await db.query('CREATE TABLE tch_profile(id uuid PRIMARY KEY,email text,display_name text,role text,status text,creator_id bigint)');
    await db.query('CREATE TABLE tch_audit_log(request_id uuid,actor_id uuid,actor_email text,actor_role text,method text,path text,resource_id text,field_names jsonb,response_status int)');
    const admin = {id:randomUUID(),role:'super_admin'}, member = {id:randomUUID(),role:'tch_member'}, outsider = {id:randomUUID(),role:'tch_member'}, creator = {id:randomUUID(),role:'creator',creatorId:'1'}, other = {id:randomUUID(),role:'creator',creatorId:'2'}, accounts = {id:randomUUID(),role:'accounts'};
    for (const actor of [admin,member,outsider,creator,other,accounts]) await db.query("INSERT INTO tch_profile VALUES($1,$2,'Person',$3,'approved',$4)",[actor.id,`${actor.id}@test.local`,actor.role,'creatorId' in actor ? actor.creatorId : null]);
    const runner = db.createQueryRunner(); await runner.connect();
    const migration = new AddCampaignBriefs1753400000000();
    await migration.up(runner); await migration.down(runner); await migration.up(runner);
    const service = new CampaignContentService(db);
    await assert.rejects(service.getAgencyBrief(outsider,'1'), {status:404});
    await assert.rejects(service.getAgencyBrief(accounts,'1'), {status:403});
    await service.setAssignments(admin,'1',{version:0,members:[{user_id:member.id,can_publish:false}],creator_ids:['1']});
    const content = {...blankBrief(),objective:'Coffee launch',product_context:'Morning routine',no_mandatory_messages:true,deliverables:[{id:randomUUID(),platform:'instagram' as const,format:'Reel',quantity:1,specifications:'',due_date:'2026-10-01'}]};
    const saved = await service.saveDraft(member,'1',{version:0,content});
    await assert.rejects(service.share(member,'1',{version:saved.version}),{status:403});
    await assert.rejects(service.getCreatorBrief(creator,'1'),{status:404});
    const published = await Promise.all([service.share(admin,'1',{version:saved.version}),service.share(admin,'1',{version:saved.version})]);
    assert.equal(published[0].id,published[1].id);
    const outcomes = await Promise.allSettled([service.saveDraft(member,'1',{version:1,content:{...content,objective:'Private A'}}),service.saveDraft(member,'1',{version:1,content:{...content,objective:'Private B'}})]);
    assert.equal(outcomes.filter(v => v.status==='fulfilled').length,1);
    const visible = await service.getCreatorBrief(creator,'1');
    assert.equal(visible.content.objective,content.objective);
    assert.ok(!('draft' in visible));
    await assert.rejects(service.getCreatorBrief(other,'1'),{status:404});
    await assert.rejects(service.getVersion(admin,'2',published[0].id),{status:404});
    assert.equal((await service.listCreatorBriefs(creator,1,20)).items.length,1);
    const conceptMigration=new AddContentConcepts1753500000000();
    await conceptMigration.up(runner); await conceptMigration.down(runner); await conceptMigration.up(runner);
    const concepts=new ContentConceptService(db);
    const draft={title:'Morning routine',hook:'Wake up',outline:'Show the product',script:'Private script',cta:'Explore',requirements:''};
    const created=await concepts.save(creator,'1',{version:0,brief_revision_id:published[0].id,content:draft}) as {id:string;revision_id:string;version:number};
    assert.equal((await concepts.list(admin,'1')).items.length,0);
    assert.equal((await concepts.history(admin,'1',created.id)).revisions.length,0);
    await assert.rejects(concepts.save(other,'1',{version:1,brief_revision_id:published[0].id,content:draft},created.id),{status:404});
    await concepts.action(creator,'1',created.id,{version:1,revision_id:created.revision_id,action:'submit'});
    assert.equal((await concepts.list(admin,'1')).items[0].content.script,'Private script');
    await concepts.comment(admin,'1',created.id,{revision_id:created.revision_id,section:'hook',message:'Internal only',visibility:'internal'});
    assert.equal((await concepts.history(creator,'1',created.id)).comments.length,0);
    await assert.rejects(concepts.action(member,'1',created.id,{version:2,revision_id:created.revision_id,action:'approved'}),{status:403});
    await concepts.action(member,'1',created.id,{version:2,revision_id:created.revision_id,action:'changes_requested',message:'Show the product sooner'});
    const edited=await concepts.save(creator,'1',{version:3,brief_revision_id:published[0].id,content:{...draft,script:'New private script'}},created.id) as typeof created;
    assert.equal((await concepts.list(admin,'1')).items[0].content.script,'Private script');
    await assert.rejects(concepts.action(admin,'1',created.id,{version:4,revision_id:created.revision_id,action:'approved'}),{status:409});
    await concepts.action(creator,'1',created.id,{version:4,revision_id:edited.revision_id,action:'submit'});
    const approvals=await Promise.allSettled([concepts.action(admin,'1',created.id,{version:5,revision_id:edited.revision_id,action:'approved'}),concepts.action(admin,'1',created.id,{version:5,revision_id:edited.revision_id,action:'approved'})]);
    assert.equal(approvals.filter(r=>r.status==='fulfilled').length,1);
    await service.share(admin,'1',{version:2});
    assert.equal((await concepts.list(creator,'1')).items[0].stale_brief,true);
    await assert.rejects(concepts.save(creator,'1',{version:6,brief_revision_id:published[0].id,content:draft},created.id),{status:409});
    await assert.rejects(service.setAssignments(admin,'1',{version:0,members:[],creator_ids:[]}),{status:409});
    await service.setAssignments(admin,'1',{version:1,members:[],creator_ids:[]});
    await assert.rejects(service.getCreatorBrief(creator,'1'),{status:404});
    await assert.rejects(concepts.history(creator,'1',created.id),{status:404});
    await assert.rejects(service.saveDraft(member,'1',{version:2,content}),{status:404});
    await assert.rejects(db.query('DELETE FROM tch_campaign WHERE id=1'));
    await assert.rejects(migration.down(runner), /history/);
    await runner.release();
  } finally { await db.destroy(); await root.query(`DROP SCHEMA ${schema} CASCADE`); await root.destroy(); }
});
