# Generated by Django 6.0.4 on 2026-04-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='location',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='creator',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='ops_manager',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_url',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name='DropOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name_raw', models.CharField(blank=True, max_length=200)),
                ('drop_off_date', models.DateField(blank=True, null=True)),
                ('drop_off_date_note', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('learning', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text="e.g. '1 year', '8 months'", max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoffs', to='tch.creator')),
            ],
            options={
                'ordering': ['-drop_off_date', '-id'],
            },
        ),
    ]
