# Generated by Django 6.0.5 on 2026-06-02 09:31

import django.db.models.deletion
import tch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0003_alter_commercialdeal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('Agreement', 'Agreement'), ('Bank', 'Bank Details'), ('PAN', 'PAN'), ('GST', 'GST'), ('Other', 'Other')], default='Other', max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to=tch.models.creator_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tch.creator')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
