# Generated by Django 6.0.6 on 2026-06-04 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0006_dealcreatorshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialdeal',
            name='client_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='client_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='client_invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number sent to client', max_length=120),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='client_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='client_payment_received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='client_payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Received', 'Received'), ('Overdue', 'Overdue'), ('', '')], max_length=20),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='creator_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='creator_invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='creator_invoice_number',
            field=models.CharField(blank=True, help_text='Invoice from creator', max_length=120),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='creator_payment_cycle',
            field=models.CharField(blank=True, choices=[('Immediate', 'Immediate'), ('Net15', 'Net 15'), ('Net30', 'Net 30'), ('Net45', 'Net 45'), ('Net60', 'Net 60'), ('', '')], help_text='Payment cycle for creator payout', max_length=20),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='creator_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='creator_payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('', '')], max_length=20),
        ),
    ]
