# Generated by Django 6.0.6 on 2026-06-04 16:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0007_finance_invoice_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('invited_date', models.DateField(blank=True, null=True)),
                ('response', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('NoResponse', 'No Response'), ('', '')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invites', to='tch.creator')),
            ],
            options={
                'ordering': ['-event_date', 'creator__name'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('Baseline', 'Baseline (Day 0)'), ('Quarterly', 'Quarterly')], default='Quarterly', max_length=20)),
                ('snapshot_date', models.DateField()),
                ('platform', models.CharField(default='Instagram', max_length=40)),
                ('followers', models.IntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='As percentage, e.g. 3.5 = 3.5%', max_digits=6)),
                ('estimated_reach', models.IntegerField(default=0)),
                ('revenue_last_3m', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Estimated revenue in last 3 months (INR)', max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_snapshots', to='tch.creator')),
            ],
            options={
                'ordering': ['creator__name', 'snapshot_date'],
            },
        ),
    ]
