# Generated by Django 6.0.5 on 2026-06-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0010_alertdismissal'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contractingcompliance',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creator',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dropoff',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employeeweeklyreport',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='socialmediasnapshot',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
