import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Payments feature: client/creator invoice documents per deal, plus a
 * completed_at marker on the deal so the "clear payment" alert has an anchor
 * date once invoices are in.
 */
export class PaymentsDealDocuments1751900000000 implements MigrationInterface {
  name = 'PaymentsDealDocuments1751900000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE tch_commercialdeal ADD COLUMN completed_at date
    `);

    await queryRunner.query(`
      CREATE TABLE tch_dealdocument (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        deal_id bigint NOT NULL REFERENCES tch_commercialdeal(id) ON DELETE CASCADE,
        doc_type varchar(20) NOT NULL DEFAULT 'ClientInvoice',
        label varchar(200) NOT NULL DEFAULT '',
        file varchar(500) NOT NULL DEFAULT '',
        uploaded_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_dealdocument_deal ON tch_dealdocument (deal_id)`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS idx_dealdocument_deal`);
    await queryRunner.query(`DROP TABLE IF EXISTS tch_dealdocument`);
    await queryRunner.query(`ALTER TABLE tch_commercialdeal DROP COLUMN completed_at`);
  }
}
