import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Initial schema, replacing the retired Django backend.
 *
 * The previous Django app created these same tables (plus its auth/session
 * system tables). All of them were verified empty before this backend was
 * written, so the migration drops the legacy tables and recreates the domain
 * schema under TypeORM's ownership. Unlike Django — which enforced FK
 * on_delete in Python — referential actions here live in the database
 * (CASCADE / RESTRICT / SET NULL).
 */
export class InitialSchema1751800000000 implements MigrationInterface {
  name = 'InitialSchema1751800000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Legacy Django system + domain tables (empty; backend removed in 33673d6).
    await queryRunner.query(`
      DROP TABLE IF EXISTS
        django_admin_log, auth_user_user_permissions, auth_user_groups,
        auth_group_permissions, auth_permission, auth_group, auth_user,
        django_session, django_content_type, django_migrations,
        tch_dealcreatorshare, tch_commercialdeal, tch_contractingcompliance,
        tch_creatordocument, tch_socialmediasnapshot, tch_eventinvite,
        tch_dropoff, tch_campaign, tch_creator, tch_employeeweeklyreport,
        tch_alertdismissal
      CASCADE
    `);

    await queryRunner.query(`
      CREATE TABLE tch_creator (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(200) NOT NULL UNIQUE,
        category varchar(200) NOT NULL DEFAULT '',
        source varchar(20) NOT NULL DEFAULT '',
        stage varchar(20) NOT NULL DEFAULT '',
        relationship varchar(20) NOT NULL DEFAULT 'Friend',
        status varchar(10) NOT NULL DEFAULT 'Active',
        doj date,
        doj_note varchar(120) NOT NULL DEFAULT '',
        profile_url varchar(400) NOT NULL DEFAULT '',
        location varchar(80) NOT NULL DEFAULT '',
        ops_manager varchar(80) NOT NULL DEFAULT '',
        notes text NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        version integer NOT NULL DEFAULT 1 CHECK (version >= 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE tch_campaign (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(255) NOT NULL UNIQUE,
        brand varchar(200) NOT NULL DEFAULT '',
        status varchar(10) NOT NULL DEFAULT 'Active',
        start_date date,
        end_date date,
        notes text NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now(),
        version integer NOT NULL DEFAULT 1 CHECK (version >= 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE tch_creatordocument (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        creator_id bigint NOT NULL REFERENCES tch_creator(id) ON DELETE CASCADE,
        doc_type varchar(20) NOT NULL DEFAULT 'Other',
        label varchar(200) NOT NULL DEFAULT '',
        file varchar(300) NOT NULL DEFAULT '',
        uploaded_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_creatordocument_creator ON tch_creatordocument (creator_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE tch_contractingcompliance (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        creator_id bigint NOT NULL UNIQUE REFERENCES tch_creator(id) ON DELETE CASCADE,
        final_meeting varchar(1) NOT NULL DEFAULT '',
        agreement_sent varchar(1) NOT NULL DEFAULT '',
        agreement_signed varchar(1) NOT NULL DEFAULT '',
        bank_verified varchar(1) NOT NULL DEFAULT '',
        time_to_sign varchar(120) NOT NULL DEFAULT '',
        renewal_date date,
        renewal_note varchar(120) NOT NULL DEFAULT '',
        version integer NOT NULL DEFAULT 1 CHECK (version >= 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE tch_commercialdeal (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        confirmation_date date,
        e_invoice_date date,
        creator_id bigint REFERENCES tch_creator(id) ON DELETE RESTRICT,
        creator_name_raw varchar(200) NOT NULL DEFAULT '',
        tch_poc varchar(120) NOT NULL DEFAULT '',
        agency_commission_agreed varchar(120) NOT NULL DEFAULT '',
        direction varchar(16) NOT NULL DEFAULT 'Outbound',
        total_fee numeric(14,2) NOT NULL DEFAULT 0,
        agency_fee_pct numeric(6,4) NOT NULL DEFAULT 0,
        agency_fee_inr numeric(14,2) NOT NULL DEFAULT 0,
        creator_fee numeric(14,2) NOT NULL DEFAULT 0,
        billing_entity varchar(120) NOT NULL DEFAULT '',
        brand varchar(200) NOT NULL DEFAULT '',
        brand_poc varchar(200) NOT NULL DEFAULT '',
        campaign_id bigint REFERENCES tch_campaign(id) ON DELETE SET NULL,
        deliverables varchar(255) NOT NULL DEFAULT '',
        ro_number varchar(80) NOT NULL DEFAULT '',
        campaign_over varchar(1) NOT NULL DEFAULT '',
        invoice_received varchar(1) NOT NULL DEFAULT '',
        payment_cleared varchar(1) NOT NULL DEFAULT '',
        e_invoice_number varchar(80) NOT NULL DEFAULT '',
        payment_received varchar(1) NOT NULL DEFAULT '',
        client_invoice_number varchar(120) NOT NULL DEFAULT '',
        client_invoice_date date,
        client_invoice_amount numeric(14,2) NOT NULL DEFAULT 0,
        client_payment_status varchar(20) NOT NULL DEFAULT '',
        client_payment_received_amount numeric(14,2) NOT NULL DEFAULT 0,
        client_payment_date date,
        creator_invoice_number varchar(120) NOT NULL DEFAULT '',
        creator_invoice_date date,
        creator_invoice_amount numeric(14,2) NOT NULL DEFAULT 0,
        creator_payment_status varchar(20) NOT NULL DEFAULT '',
        creator_payment_cycle varchar(20) NOT NULL DEFAULT '',
        creator_payment_date date,
        comments text NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now(),
        version integer NOT NULL DEFAULT 1 CHECK (version >= 0)
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_commercialdeal_creator ON tch_commercialdeal (creator_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_commercialdeal_campaign ON tch_commercialdeal (campaign_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE tch_dealcreatorshare (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        deal_id bigint NOT NULL REFERENCES tch_commercialdeal(id) ON DELETE CASCADE,
        creator_id bigint REFERENCES tch_creator(id) ON DELETE RESTRICT,
        creator_name_raw varchar(200) NOT NULL DEFAULT '',
        total_fee numeric(14,2) NOT NULL DEFAULT 0,
        agency_fee_pct numeric(6,4) NOT NULL DEFAULT 0,
        agency_fee_inr numeric(14,2) NOT NULL DEFAULT 0,
        creator_fee numeric(14,2) NOT NULL DEFAULT 0
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_dealcreatorshare_deal ON tch_dealcreatorshare (deal_id)`,
    );
    await queryRunner.query(
      `CREATE INDEX idx_dealcreatorshare_creator ON tch_dealcreatorshare (creator_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE tch_dropoff (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        creator_id bigint REFERENCES tch_creator(id) ON DELETE SET NULL,
        creator_name_raw varchar(200) NOT NULL DEFAULT '',
        drop_off_date date,
        drop_off_date_note varchar(120) NOT NULL DEFAULT '',
        reason text NOT NULL DEFAULT '',
        learning text NOT NULL DEFAULT '',
        duration varchar(80) NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now(),
        version integer NOT NULL DEFAULT 1 CHECK (version >= 0)
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_dropoff_creator ON tch_dropoff (creator_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE tch_socialmediasnapshot (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        creator_id bigint NOT NULL REFERENCES tch_creator(id) ON DELETE CASCADE,
        snapshot_type varchar(20) NOT NULL DEFAULT 'Quarterly',
        snapshot_date date NOT NULL,
        platform varchar(40) NOT NULL DEFAULT 'Instagram',
        followers integer NOT NULL DEFAULT 0,
        engagement_rate numeric(6,3) NOT NULL DEFAULT 0,
        estimated_reach integer NOT NULL DEFAULT 0,
        revenue_last_3m numeric(14,2) NOT NULL DEFAULT 0,
        notes text NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now(),
        version integer NOT NULL DEFAULT 1 CHECK (version >= 0)
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_socialmediasnapshot_creator ON tch_socialmediasnapshot (creator_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE tch_eventinvite (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        creator_id bigint NOT NULL REFERENCES tch_creator(id) ON DELETE CASCADE,
        event_name varchar(255) NOT NULL,
        event_date date NOT NULL,
        invited_date date,
        response varchar(20) NOT NULL DEFAULT '',
        notes text NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now(),
        version integer NOT NULL DEFAULT 1 CHECK (version >= 0)
      )
    `);
    await queryRunner.query(
      `CREATE INDEX idx_eventinvite_creator ON tch_eventinvite (creator_id)`,
    );

    await queryRunner.query(`
      CREATE TABLE tch_employeeweeklyreport (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        week_ending date,
        employee_name varchar(120) NOT NULL,
        new_outreach integer NOT NULL DEFAULT 0,
        paid_confirmations varchar(255) NOT NULL DEFAULT '',
        revenue_locked numeric(14,2) NOT NULL DEFAULT 0,
        profit_locked numeric(14,2) NOT NULL DEFAULT 0,
        barter_confirmations varchar(255) NOT NULL DEFAULT '',
        live_campaigns integer NOT NULL DEFAULT 0,
        action_points text NOT NULL DEFAULT '',
        version integer NOT NULL DEFAULT 1 CHECK (version >= 0)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE tch_alertdismissal (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key varchar(255) NOT NULL UNIQUE,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DROP TABLE IF EXISTS
        tch_dealcreatorshare, tch_commercialdeal, tch_contractingcompliance,
        tch_creatordocument, tch_socialmediasnapshot, tch_eventinvite,
        tch_dropoff, tch_campaign, tch_creator, tch_employeeweeklyreport,
        tch_alertdismissal
      CASCADE
    `);
  }
}
