import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddCreatorInvoices1752200000000 implements MigrationInterface {
  name = 'AddCreatorInvoices1752200000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE tch_creatorinvoice (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        deal_id bigint NOT NULL REFERENCES tch_commercialdeal(id) ON DELETE CASCADE,
        creator_id bigint NOT NULL REFERENCES tch_creator(id) ON DELETE RESTRICT,
        invoice_number varchar(120) NOT NULL DEFAULT '',
        invoice_date date,
        invoice_amount numeric(14,2) NOT NULL DEFAULT 0,
        payment_status varchar(20) NOT NULL DEFAULT '',
        payment_cycle varchar(20) NOT NULL DEFAULT '',
        payment_date date,
        label varchar(200) NOT NULL DEFAULT '',
        file varchar(500) NOT NULL DEFAULT '',
        uploaded_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        version integer NOT NULL DEFAULT 1 CHECK (version >= 1),
        CONSTRAINT uq_creatorinvoice_deal_creator UNIQUE (deal_id, creator_id)
      )
    `);
    await queryRunner.query(`CREATE INDEX idx_creatorinvoice_creator ON tch_creatorinvoice (creator_id, uploaded_at DESC)`);
    await queryRunner.query(`CREATE INDEX idx_creatorinvoice_deal ON tch_creatorinvoice (deal_id)`);

    // Move only unambiguous legacy invoices. A split campaign is safe when it
    // has exactly one distinct creator; otherwise its old document remains in
    // tch_dealdocument for explicit assignment in the next UI phase.
    await queryRunner.query(`
      WITH share_creators AS (
        SELECT deal_id, COUNT(DISTINCT creator_id) AS creator_count, MIN(creator_id) AS creator_id
        FROM tch_dealcreatorshare
        WHERE creator_id IS NOT NULL
        GROUP BY deal_id
      ), candidates AS (
        SELECT DISTINCT ON (doc.deal_id)
          doc.id AS document_id,
          doc.deal_id,
          CASE
            WHEN COALESCE(sc.creator_count, 0) = 1 THEN sc.creator_id
            WHEN COALESCE(sc.creator_count, 0) = 0 THEN deal.creator_id
            ELSE NULL
          END AS creator_id,
          doc.label,
          doc.file,
          doc.uploaded_at,
          deal.creator_invoice_number,
          deal.creator_invoice_date,
          deal.creator_invoice_amount,
          deal.creator_payment_status,
          deal.creator_payment_cycle,
          deal.creator_payment_date
        FROM tch_dealdocument doc
        JOIN tch_commercialdeal deal ON deal.id = doc.deal_id
        LEFT JOIN share_creators sc ON sc.deal_id = doc.deal_id
        WHERE doc.doc_type = 'CreatorInvoice'
        ORDER BY doc.deal_id, doc.uploaded_at DESC, doc.id DESC
      )
      INSERT INTO tch_creatorinvoice (
        deal_id, creator_id, invoice_number, invoice_date, invoice_amount,
        payment_status, payment_cycle, payment_date, label, file, uploaded_at, updated_at
      )
      SELECT
        deal_id, creator_id, creator_invoice_number, creator_invoice_date,
        creator_invoice_amount, creator_payment_status, creator_payment_cycle,
        creator_payment_date, label, file, uploaded_at, uploaded_at
      FROM candidates
      WHERE creator_id IS NOT NULL
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Legacy deal-document rows were retained during the copy/backfill, so
    // reverting only needs to remove the new structured records.
    await queryRunner.query(`DROP INDEX IF EXISTS idx_creatorinvoice_deal`);
    await queryRunner.query(`DROP INDEX IF EXISTS idx_creatorinvoice_creator`);
    await queryRunner.query(`DROP TABLE tch_creatorinvoice`);
  }
}
