import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddPaymentTransactions1752500000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS tch_payment_transaction (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        transaction_date date NOT NULL,
        vendor_name varchar(200) NOT NULL,
        utr_or_ref varchar(120) NOT NULL,
        debit_amount numeric(14,2) NOT NULL DEFAULT 0,
        credit_amount numeric(14,2) NOT NULL DEFAULT 0,
        deal_id bigint REFERENCES tch_commercialdeal(id) ON DELETE SET NULL,
        creator_id bigint REFERENCES tch_creator(id) ON DELETE SET NULL,
        notes text NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS tch_payment_transaction`);
  }
}
