import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddTdsEntries1752600000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS tch_tds_entry (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        creator_id bigint NOT NULL REFERENCES tch_creator(id) ON DELETE RESTRICT,
        deal_id bigint REFERENCES tch_commercialdeal(id) ON DELETE SET NULL,
        quarter varchar(20) NOT NULL,
        tds_rate numeric(6,4) NOT NULL DEFAULT 0,
        gross_amount numeric(14,2) NOT NULL DEFAULT 0,
        tds_amount numeric(14,2) NOT NULL DEFAULT 0,
        net_payable numeric(14,2) NOT NULL DEFAULT 0,
        remittance_date date,
        challan_number varchar(120) NOT NULL DEFAULT '',
        status varchar(20) NOT NULL DEFAULT 'Pending',
        notes text NOT NULL DEFAULT '',
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS tch_tds_entry`);
  }
}
