import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddAuditAndQueryIndexes1753000000000 implements MigrationInterface {
  name = 'AddAuditAndQueryIndexes1753000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS tch_audit_log (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        request_id uuid NOT NULL,
        actor_id uuid,
        actor_email varchar(255) NOT NULL DEFAULT '',
        actor_role varchar(20) NOT NULL DEFAULT '',
        method varchar(10) NOT NULL,
        path varchar(500) NOT NULL,
        resource_id varchar(120),
        field_names jsonb NOT NULL DEFAULT '[]'::jsonb,
        response_status smallint NOT NULL,
        created_at timestamptz NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_audit_created ON tch_audit_log (created_at DESC, id DESC)`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_audit_actor ON tch_audit_log (actor_id, created_at DESC)`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_deal_fy_month ON tch_commercialdeal (billing_fy_start, billing_month)`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_deal_campaign_period ON tch_commercialdeal (campaign_id, billing_period)`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_payment_date ON tch_payment_transaction (transaction_date DESC, id DESC)`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_tds_creator_status ON tch_tds_entry (creator_id, status, created_at DESC)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS idx_tds_creator_status`);
    await queryRunner.query(`DROP INDEX IF EXISTS idx_payment_date`);
    await queryRunner.query(`DROP INDEX IF EXISTS idx_deal_campaign_period`);
    await queryRunner.query(`DROP INDEX IF EXISTS idx_deal_fy_month`);
    await queryRunner.query(`DROP TABLE IF EXISTS tch_audit_log`);
  }
}
