# Generated by Django 6.0.4 on 2026-04-15 09:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, choices=[('EMW', 'EMW'), ('TCH', 'TCH'), ('OTHER', 'Other')], max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('Lead', 'Lead'), ('Discussing', 'Discussing'), ('Closed', 'Closed'), ('Dropped', 'Dropped')], max_length=20)),
                ('relationship', models.CharField(choices=[('Exclusive', 'Exclusive'), ('Friend', 'Friend'), ('Dropping', 'Dropping out soon'), ('NonTCH', 'Non TCH')], default='Friend', max_length=20)),
                ('doj', models.DateField(blank=True, null=True)),
                ('doj_note', models.CharField(blank=True, help_text='Free-text DOJ if unparseable', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField(blank=True, null=True)),
                ('employee_name', models.CharField(max_length=120)),
                ('new_outreach', models.IntegerField(default=0)),
                ('paid_confirmations', models.CharField(blank=True, max_length=255)),
                ('revenue_locked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('profit_locked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('barter_confirmations', models.CharField(blank=True, max_length=255)),
                ('live_campaigns', models.IntegerField(default=0)),
                ('action_points', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-week_ending', 'employee_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractingCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_meeting', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('', '')], max_length=1)),
                ('agreement_sent', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('', '')], max_length=1)),
                ('agreement_signed', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('', '')], max_length=1)),
                ('bank_verified', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('', '')], max_length=1)),
                ('time_to_sign', models.CharField(blank=True, max_length=120)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('renewal_note', models.CharField(blank=True, max_length=120)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contracting', to='tch.creator')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('e_invoice_date', models.DateField(blank=True, null=True)),
                ('creator_name_raw', models.CharField(blank=True, help_text='Raw name string for non-TCH / outsiders without a Creator row', max_length=200)),
                ('agency_commission_agreed', models.CharField(blank=True, max_length=120)),
                ('direction', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound'), ('MarkUp', 'Mark Up')], default='Outbound', max_length=16)),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('agency_fee_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Fractional, e.g. 0.20 = 20%', max_digits=6)),
                ('agency_fee_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Profit to TCH', max_digits=14)),
                ('creator_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('billing_entity', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('campaign', models.CharField(blank=True, max_length=255)),
                ('deliverables', models.CharField(blank=True, max_length=255)),
                ('ro_number', models.CharField(blank=True, max_length=80)),
                ('campaign_over', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('', '')], max_length=1)),
                ('invoice_received', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('', '')], max_length=1)),
                ('payment_cleared', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('', '')], max_length=1)),
                ('e_invoice_number', models.CharField(blank=True, max_length=80)),
                ('payment_received', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N'), ('', '')], max_length=1)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='tch.creator')),
            ],
            options={
                'ordering': ['-confirmation_date', '-id'],
            },
        ),
    ]
