# Generated by Django 6.0.5 on 2026-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0002_creator_location_creator_notes_creator_ops_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialdeal',
            options={'ordering': [models.OrderBy(models.F('confirmation_date'), nulls_first=True), 'id']},
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='brand_poc',
            field=models.CharField(blank=True, help_text='Brand-side point of contact (name / detail)', max_length=200),
        ),
        migrations.AddField(
            model_name='commercialdeal',
            name='tch_poc',
            field=models.CharField(blank=True, help_text='TCH person who worked on this deal', max_length=120),
        ),
    ]
