# Generated by Django 6.0.5 on 2026-06-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0004_creatordocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
