# Generated by Django 6.0.5 on 2026-06-02 10:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0005_creator_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCreatorShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name_raw', models.CharField(blank=True, max_length=200)),
                ('total_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('agency_fee_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('agency_fee_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('creator_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_shares', to='tch.creator')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_shares', to='tch.commercialdeal')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
