# Generated by Django 6.0.6 on 2026-06-05 10:04

import django.db.models.deletion
import tch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0008_social_snapshots_and_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialdeal',
            name='client_invoice_due_date',
            field=models.DateField(blank=True, help_text='When client payment is due', null=True),
        ),
        migrations.CreateModel(
            name='InvoiceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('creator', 'Creator Invoice'), ('client', 'Client Invoice')], max_length=10)),
                ('file', models.FileField(upload_to=tch.models.invoice_upload_path)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Accepted', 'Accepted'), ('NeedsRevision', 'Needs Revision'), ('Cleared', 'Cleared')], default='Received', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='For client invoices — payment due date', null=True)),
                ('comments', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_files', to='tch.commercialdeal')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
