# Generated by Django 6.0.6 on 2026-06-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tch', '0011_campaign_version_commercialdeal_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatordocument',
            name='doc_type',
            field=models.CharField(choices=[('Agreement', 'Agreement'), ('Bank', 'Bank Details'), ('PAN', 'PAN'), ('Aadhar', 'Aadhar'), ('Cheque', 'Cancelled Cheque'), ('GST', 'GST'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
