'use client';
import Link from 'next/link';
import { useKit,useSocialAccounts,useSavedSnapshots } from './kit-queries';
import { starterDraft,metric,importedDate } from '@/lib/creator-kit';
import { CreatorImage } from '@/components/CreatorKitView';
import { CreateKitForm,ImportProgress } from './ImportActions';
export default function CreatorOverviewPage(){
  const accounts=useSocialAccounts(),kit=useKit(),snapshots=useSavedSnapshots(accounts.data??[]);
  if(accounts.isLoading||kit.isLoading)return <div className="creator-loading">Making room for your next big idea…</div>;
  if(accounts.error||kit.error)return <div role="alert">We couldn’t load your workspace. <button className="cf-link" onClick={()=>{accounts.refetch();kit.refetch();}}>Try again</button></div>;
  const saved=accounts.data?.filter(a=>a.snapshot_id)??[],account=saved[0];
  const draft=kit.data?starterDraft(kit.data,accounts.data??[]):null;
  const name=(draft?.profile.display_name||account?.profile?.display_name||'creator').split(/[ |]/)[0];
  const posts=snapshots.flatMap(s=>s.data?.posts??[]).sort((a,b)=>(b.published_at??'').localeCompare(a.published_at??''));
  const steps=[{title:'Make it yours',detail:'Add your story and what you love creating.',href:'/creator-portal/profile',done:!!kit.data?.version&&!!draft?.profile.biography},{title:'Pick your standouts',detail:'Choose the work you want brands to see.',href:'/creator-portal/portfolio',done:!!draft?.featured_posts.length},{title:'Put yourself out there',detail:'Publish your kit and share your link.',href:'/creator-portal/media-kit',done:!!kit.data?.published_revision}];
  return <div className="creator-flow"><div className="cf-top creator-welcome"><div><p className="cf-step">GOOD THINGS START HERE</p><h1>Hi {name},<br/>make room for what’s next<span className="creator-dot">.</span></h1><p className="cf-muted">Your creativity. Your story. Your next collaboration.</p></div>{account&&<Link className="creator-button" href="/creator-portal/media-kit">Preview brand kit ↗</Link>}</div>
    {!account&&<CreateKitForm/>}{accounts.data?.map(a=><ImportProgress key={a.id} account={a}/>)}
    {account&&<><div className="creator-home-grid"><section className="creator-person-card"><CreatorImage src={account.profile?.image_url??null} alt={draft?.profile.display_name||account.username} className="creator-person-photo"/><div className="creator-person-copy"><span className="creator-glass-tag">Your creative corner</span><h2>{draft?.profile.display_name||account.username}</h2><p>@{account.username}</p><Link href="/creator-portal/profile">Edit your profile ↗</Link></div></section>
      <section className="cf-panel creator-audience-card"><div className="cf-top"><h2>Your audience</h2><span className="creator-round-icon" aria-hidden="true">↗</span></div><div className="creator-big-number">{metric(account.profile?.followers)}</div><p className="cf-muted">Instagram followers</p><div className="creator-audience-art" aria-hidden="true"><span/><span/><span/><span/><span/></div><p className="cf-muted">Updated {importedDate(account.collected_at)}</p></section>
      <section className="cf-panel creator-kit-card"><div className="cf-top"><h2>Your brand kit</h2><span className="creator-round-icon" aria-hidden="true">✳</span></div><div className="creator-kit-mark" aria-hidden="true">✳</div><h3>{kit.data?.published_revision?'Ready for the world.':'Ready when you are.'}</h3><p className="cf-muted">{draft?.featured_posts.length??0} featured posts · {kit.data?.published_revision?'Published':'Private draft'}</p><Link className="creator-button creator-button-light" href="/creator-portal/media-kit">{kit.data?.published_revision?'Manage your kit':'Finish your kit'} ↗</Link></section>
      <section className="creator-next-card"><div className="cf-top"><h2>A few small steps.<br/>A great first impression.</h2><span className="cf-badge">{steps.filter(s=>s.done).length}/3</span></div>{steps.map((step,i)=><Link key={step.href} className="creator-step-row" href={step.href}><span className={step.done?'creator-step-number complete':'creator-step-number'}>{step.done?'✓':i+1}</span><div><h3>{step.title}</h3><p>{step.detail}</p></div><span aria-hidden="true">↗</span></Link>)}</section></div>
      <section><div className="cf-top" style={{marginBottom:20}}><div><h2>Fresh from your feed</h2><p className="cf-muted">A little window into what you create.</p></div><Link className="cf-link" href="/creator-portal/portfolio">See all {posts.length} posts ↗</Link></div><div className="creator-recent-grid">{posts.slice(0,4).map(post=><Link href="/creator-portal/portfolio" className="creator-recent-post" key={post.platform_post_id}><CreatorImage src={post.image_url} alt={post.caption?.slice(0,80)||'Your content'} className="cf-thumb"/><div><span>{post.content_type||'Post'}</span><p>{post.caption?.slice(0,95)||'Your next standout piece'}</p></div></Link>)}</div></section></>}
  </div>;
}
